#!/usr/bin/env bash
WARN=1750
CRIT=2500

source ~/.i3/blocks/colors

# start with clean values
cpu_speed=0
total=0
count=0

for i in $( cat /proc/cpuinfo | grep MHz | awk '{print $4}' | awk -F\. '{print $1}' )
do
  total=$( echo $total+$i | bc )
  ((count++))
done
cpu_speed=$( echo "scale=0; $total / $count" | bc -l )

if [ $cpu_speed -lt $WARN ]; then
  COLOR=$OK_COLOR
elif [[ $cpu_speed -lt $CRIT ]]; then
  COLOR=$WARN_COLOR
elif [[ $cpu_speed -gt $CRIT ]]; then
  COLOR=$CRIT_COLOR
fi

echo "<span color='$COLOR'>$cpu_speed Mhz</span>"
