#!/bin/bash
# createlinks
# creates symlinks to a dotfiles repo

# Alexander Swen
# Private contact: alex@swen.nu, 06-21811135

# CHANGELOG:
# 2013-06-25	A.Swen	created.

# SETTINGS
date=$(date +%Y%m%d)
me=$(basename $0)
mydir=$(dirname $0)
dotfiles="bash_logout bashrc cryptvolumes gitconfig gitignore gscan2pdf gtk-bookmarks profile tmux.conf xmodmap xprofile"

# FUNCTIONS
die () {
  rc=$1
  shift
  echo "==========================">&2
  echo "====    FATAL  ERROR  ====" >&2
  echo "==========================">&2
  echo "" >&2
  echo $@ >&2
  exit $rc
}

# SCRIPT
[ -d ~/dotfiles ]|| die 1 "have you cloned dotfiles to your homedir?"

for dotfile in ${dotfiles};do
  [ -f ~/.${dotfile} ] && mv ~/.${dotfile} ~/.${dotfile}-bck-dotfiles-${date}
  ln -s ~/dotfiles/${dotfile} ~/.${dotfile}
done

[ -d ~/.i3 ]||install -dm 775 ~/.i3
ln -s ~/dotfiles/i3wm-config ~/.i3/config

# END
