#!/bin/bash
# createlinks
# creates symlinks to a dotfiles repo

# Alexander Swen
# Private contact: alex@swen.nu, 06-21811135

# CHANGELOG:
# 2013-06-25	A.Swen	created.

# SETTINGS
date=$(date +%Y%m%d)
me=$(basename $0)
mydir=$(dirname $0)
dotfiles="bash_logout bash_colours bashrc gitconfig gitignore gtk-bookmarks profile tmux.conf xmodmap xprofile Xresources bash_bindings fonts puppet-lint.rc bash_functions.d toprc xsessionrc keyboard"

# FUNCTIONS
die () {
  rc=$1
  shift
  echo "==========================">&2
  echo "====    FATAL  ERROR  ====" >&2
  echo "==========================">&2
  echo "" >&2
  echo $@ >&2
  exit $rc
}

# SCRIPT
[ -d ~/dotfiles ]|| die 1 "have you cloned dotfiles to your homedir?"

for dotfile in ${dotfiles};do
  [ -L ~/.${dotfile} ] && rm ~/.${dotfile}
  [ -f ~/.${dotfile} -o -d ~/.${dotfile} ] && mv ~/.${dotfile} ~/.${dotfile}-bck-dotfiles-${date}
  ln -s ~/dotfiles/${dotfile} ~/.${dotfile}
done

[ -d ~/.i3 ]||install -dm 775 ~/.i3
[ -L ~/.i3/config ]||ln -s ~/dotfiles/i3wm-config ~/.i3/config
[ -L ~/.i3/status ]||ln -s ~/dotfiles/i3status ~/.i3/status

[ -L ~/.dircolors ]||ln -sf ~/dotfiles/dircolors-dark ~/.dircolors

[ -d ~/.config/Dharkeal ] || mkdir -p ~/.config/Dharkeal
[ -L ~/.config/Dharkeal/flameshot.ini ] || ln -s ~/dotfiles/flameshot.ini ~/.config/Dharkeal

source ~/.bashrc

# END
