#!/bin/bash

log=/home/alex/xprofile.log
exec > $log 2>&1
set -x

/usr/bin/xset b off
/usr/bin/xset b 0 0 0
/usr/bin/xset fp defaults
/usr/bin/xset +fp ~/.fonts
/usr/bin/xset +fp ~/.fonts/dina
#eval `/usr/bin/gnome-keyring-daemon --start --components=pkcs11`
/usr/bin/nm-applet&
/usr/bin/blueman-applet&
#/usr/bin/gkrellm&
/usr/bin/glipper&
/usr/bin/setxkbmap -variant euro -option -option compose:menu,lv3:ralt_switch,eurosign:5,ctrl:nocaps
/usr/bin/xmodmap ~/.xmodmap
/usr/bin/libreoffice --quickstart --nologo&
[ -x /usr/bin/numlockx ]&&/usr/bin/numlockx on
## tapping aan en geen palm op touchpad
/usr/bin/synclient TapButton1=1 PalmDetect=1 VertEdgeScroll=1 HorizEdgeScroll=1 HorizTwoFingerScroll=1 AccelFactor=0.05
#
##http://askubuntu.com/questions/46299/how-to-disable-touchpad-tapping-when-typing-on-keyboard
##http://www.webupd8.org/2009/11/ubuntu-automatically-disable-touchpad.html
/usr/bin/syndaemon -dKti2 -v

# Load NextCloud
/data/software/Nextcloud-2.3.2-x86_64.AppImage &

# start the gpg-agent
eval $(gpg-agent --daemon)
# Start the NitroKey app
# /usr/bin/nitrokey-app &

# This is here so cron can use notify-send to warn me if batery gets empty
[ -d $HOME/.dbus ] || mkdir $HOME/.dbus
env | grep DBUS_SESSION_BUS_ADDRESS > $HOME/.dbus/Xdbus
echo 'export DBUS_SESSION_BUS_ADDRESS' >> $HOME/.dbus/Xdbus
chmod 600 $HOME/.dbus/Xdbus

set +x
